<script setup>
    const props = defineProps({
        heading: String,
        content: String,
        img_src: String,
        img_alt: String,
    })
</script>

<template>
    <section>
        <div class="text-container">
            <SectionHeading :heading="heading"></SectionHeading>
            <p>
                Gencaster is a platform for building audio streaming experiences with dynamic and generative content. This allows for a unique stream per user instead of delivering the same synchronised stream to everyone (traditional radio broadcasting) or relying on on-demand interaction (current streaming/podcast platforms).
                This new way of streaming audio allows the introduction of new formats generated by user preference or interaction (e.g. a weather forecast derived from GPS location). Due to the low latency of WebRTC technology, we can achieve new ways of storytelling and story distribution that are not limited to the spoken context, but can also be used for new musical compositions.
                Our player (running on WebRTC) allows to embed this audio stream in an app or simply on a website, making the barrier for the user to listen to the stream very low.
            </p>
        </div>
        <div class="img-container">
            <img :src="img_src" :alt="img_alt">
        </div>
    </section>
</template>

<style lang="scss" scoped>
    section {
        @include gap;
        @include borderless;
        
        background-color: $green;
        color: $black;
        display: flex; 
        flex-flow: column nowrap;
        align-items: center;
        
        @include onScreen('macbook-up') {          
            flex-direction: row;
        }
    }
    
    .text-container, .img-container {
        @include padding-v($spacingS);
        
        width: 100%;
        
        @include onScreen('tablet-portrait-up') {
            @include padding-v($spacingM);
            
            width: 80%;
        }
        
        @include onScreen('macbook-up') {
            @include padding-v($spacingL);
        }
    }

    .img-container {
        @include padding-h(10%);
    }
    
</style>