name: Deploy to GitHub Pages with LFS Checkout
on:
  push:
    branches:
      - v3
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
          lfs: true
      - name: Install dependencies
        run: npm ci
      - name: Build and deploy
        run: npm run deploy
        env:
          NODE_ENV: production
          BASE_URL: https://gencaster.github.io/
      - name: Deployed successfully
        run: echo "Deployed successfully"
