name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Install dependencies
        run: npm ci
      - name: Build and deploy
        run: npm run deploy
        env:
          NODE_ENV: production
          BASE_URL: https://Gencaster.github.io/
      - name: Deployed successfully
        run: echo "Deployed successfully"

